name: neww
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.2.5
  google_fonts: ^6.1.0
  file_picker: ^10.1.7
  image_picker: ^1.0.4
  provider: ^6.1.3
  http: ^1.4.0
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Add this assets section (remove the comments if you want)
  assets:
    - assets/